<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/21 0021
 * Time: 11:28
 */

namespace TinyWeb\Helper;

use Illuminate\Database\ConnectionInterface;
use Illuminate\Database\Query\Builder;
use Illuminate\Database\Query\Grammars\Grammar;
use Illuminate\Database\Query\Processors\Processor;

class BuilderHelper extends Builder
{
    private static $_table_ext_map = [];
    private $_this_table = '';
    private $_this_db = '';

    /**
     * BuilderHelper constructor.
     * @param string $db_name
     * @param ConnectionInterface $connection
     * @param Grammar $grammar
     * @param Processor $processor
     */
    public function __construct($db_name,ConnectionInterface $connection,Grammar $grammar,Processor $processor)
    {
        parent::__construct($connection, $grammar, $processor);
        $this->_this_db = $db_name;
    }

    public function from($table)
    {
        $this->_this_table = $table;
        return parent::from($table);
    }

    public static function registerTable($db_name, $table_name, array $table_config=[]){
        $key = $db_name.'.'.$table_name;
        if( isset(self::$_table_ext_map[$key]) || empty($table_config) ){
            return false;
        }
        self::$_table_ext_map[$key] = $table_config;
        return true;
    }

    public function get($columns = array('*'))
    {
        return parent::get($columns); // TODO: Change the autogenerated stub
    }

    public function first($columns = array('*'))
    {
        return parent::first($columns); // TODO: Change the autogenerated stub
    }

}