<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/21 0021
 * Time: 11:28
 */

namespace TinyWeb\Helper;


use Illuminate\Database\Query\Builder;

class BuilderHelper extends Builder
{
    private static $_table_attach_map = [];
    private static $_table_primary_key_map = [];
    private static $_table_unique_keys = [];

    public static function registerAttach($db_name, $table_name, array $attach){
        $key = $db_name.'.'.$table_name;
        self::$_table_attach_map[$key] = isset(self::$_table_attach_map[$key]) ?  : [];
        self::$_table_attach_map[$key] = array_merge(self::$_table_attach_map[$key], $attach);
    }

    public static function registerPrimaryKey($db_name, $table_name, $primary_key){
        $key = $db_name.'.'.$table_name;
        self::$_table_primary_key_map[$key] = $primary_key;
    }

    public static function registerUniqueKeys($db_name, $table_name, array $unique_keys){
        $key = $db_name.'.'.$table_name;
        self::$_table_unique_keys[$key] = isset(self::$_table_unique_keys[$key]) ?  : [];
        self::$_table_unique_keys[$key] = array_unique(array_merge(self::$_table_unique_keys[$key], $unique_keys));
    }

    public function get($columns = array('*'))
    {
        return parent::get($columns); // TODO: Change the autogenerated stub
    }

    public function first($columns = array('*'))
    {
        return parent::first($columns); // TODO: Change the autogenerated stub
    }

}